[package]
name = "speedtestr"
version = "0.1.0"
authors = ["Zach Peters <zpeters@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.1"
reqwest = "0.10.4"
serde_derive = "1.0.114"
serde = "1.0.114" 
serde_json = "1.0.56"
failure = "0.1.8" 
rand = "0.7.3"
